name: benchmark-deploy-debug

on:
  workflow_dispatch:

jobs:
  benchmark-deploy-debug:
    uses: ./.github/workflows/actions/ci-benchmark-deploy-debug.yml
    secrets: inherit
    with:
      client-vm: benchmark-gatling
      frontend-vm: benchmark-frontend
      backend-vm: benchmark-backend
