name: benchmark-undeploy

on:
  workflow_call:
    inputs:
      frontend-vm:
        type: string
        description: 'The frontend vm to undeploy:'
        default: ''
        required: true
      backend-vm:
        type: string
        description: 'The backend vm to undeploy:'
        default: ''
        required: false
      client-vm:
        type: string
        description: 'The client vm to undeploy:'
        default: ''
        required: true

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  FRONTEND_VM: ${{ inputs.frontend-vm }}
  BACKEND_VM: ${{ inputs.backend-vm }}
  CLIENT_VM: ${{ inputs.client-vm }}
  BUCKET: ${{ vars.BUCKET }}
  ZONE: ${{ vars.ZONE }}
  MACHINE_TYPE: ${{ vars.MACHINE_TYPE }}
  IMAGE_FAMILY: ${{ vars.IMAGE_FAMILY }}
  IMAGE_PROJECT: ${{ vars.IMAGE_PROJECT }}

jobs:
  gcp-cleanup:
    name: Cleanup GCP instances and resources
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # gcp authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Cleanup GCP instances and resources
    - name: Remove GCP instances and resources
      if: always()
      run: |-
        gcloud compute instances delete $CLIENT_VM --quiet --zone $ZONE | echo
        gcloud compute instances delete $FRONTEND_VM --quiet --zone $ZONE | echo
        if [ -n $BACKEND_VM ]; then
          gcloud compute instances delete $BACKEND_VM --quiet --zone $ZONE | echo
        fi
        gsutil rm -f gs://$BUCKET/apps/* | echo
        gsutil rm -f gs://$BUCKET/results/* | echo
