name: benchmark-deploy

on:
  workflow_call:
    inputs:
      app:
        type: string
        description: 'The application to test:'
        default: ''
        required: true
      protocol:
        type: string
        description: 'The protocol used (H1,H1S,H2,H2C):'
        default: ''
        required: true
      simulations:
        description: 'List of simulation applications:'
        required: true
        type: string
        default: ''
      dependencies:
        description: 'List of gh project dependencies to track:'
        required: true
        type: string
        default: ''
      duration:
        description: 'Test duration (in minutes):'
        required: false
        type: string
        default: '5'
      increment:
        description: 'Gatling increment:'
        required: false
        type: string
        default: '128'
      steps:
        description: 'Gatling steps:'
        required: false
        type: string
        default: '32'
      alert-threshold:
        description: 'Alert threshold like "150%". Percentage indicating how worse the current benchmark result is, e.g: 150% means that an alert happens when current benchmark result is 1.5x worse than previous:'
        required: false
        type: string
        default: '125%'
      force-bench:
        type: boolean
        description: Forces benchmark even if there's no changes
        default: true
        required: false
    outputs:
      changed:
        description: "Some commits have been done since last benchmark"
        value: ${{ jobs.init-benchmark.outputs.changed }}

env:
  SCRIPTS_DIR: ./main-repo/.github/scripts
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVER_INSTANCE: ${{ vars.SERVER_INSTANCE }}
  CLIENT_INSTANCE: ${{ vars.CLIENT_INSTANCE }}
  BUCKET: ${{ vars.BUCKET }}
  ZONE: ${{ vars.ZONE }}
  MACHINE_TYPE: ${{ vars.MACHINE_TYPE }}
  SIMULATIONS: ${{ inputs.simulations || vars.SIMULATIONS }}
  INCREMENT: ${{ inputs.increment || vars.INCREMENT }}
  DURATION: ${{ inputs.duration || vars.DURATION }}
  STEPS: ${{ inputs.steps || vars.STEPS }}
  ALERT_THRESHOLD: ${{ inputs.alert-threshold || vars.ALERT_THRESHOLD }}
  APP: ${{ inputs.app }}
  PROTOCOL: ${{ inputs.protocol }}
  APP_PROTOCOL: ${{ inputs.app }}-${{ inputs.protocol }}
  DEPENDENCIES: ${{ inputs.dependencies }}

jobs:

  init-benchmark:
    name: Initialize benchmark
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_updated.outputs.CHANGED }}
      commits: ${{ steps.check_updated.outputs.COMMITS }}
      commits_diff: ${{ steps.check_updated.outputs.COMMITS_DIFF }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          ref: 'main'
          path: main-repo
          fetch-depth: 0

      - name: Check for updates
        id: check_updated
        run: |-
          . ${SCRIPTS_DIR}/libs.sh
          git checkout gh-pages
          check_for_new_commits "$DEPENDENCIES" bench/$APP_PROTOCOL/Trends/.history $GITHUB_OUTPUT

  run-benchmark:
    name: Deploy benchmark
    needs: init-benchmark
    if: needs.init-benchmark.outputs.changed == 'true' || github.event.inputs.force-bench == 'true'
    runs-on: ubuntu-latest
    env:
      JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          ref: 'main'
          path: main-repo
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # GCP authentication via credentials json (TODO replace by OpenId)
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Maven/Gradle Compile
        shell: bash
        run: |-
          if [ -f pom.xml ]; then mvn --quiet -B package --file pom.xml; fi
          if [ -f build.gradle ]; then ./gradlew build; fi

      - name: Copy application to server bucket
        run: |-
          jarfile=$(find . -name "$APP.jar") 
          gsutil cp $jarfile gs://$BUCKET/apps/;

      # Create the server VM
      - name: Create Server
        run: |-
          gcloud compute instances create-with-container $SERVER_INSTANCE \
            --machine-type=$MACHINE_TYPE \
            --scopes="userinfo-email,storage-rw" \
            --zone=$ZONE \
            --tags=benchmark-tag \
            --network=default \
            --container-image=gcr.io/$PROJECT_ID/$SERVER_INSTANCE-image:latest \
            --container-restart-policy=never \
            --container-env=PROJECT_ID=$PROJECT_ID,BUCKET=$BUCKET,APP=$APP,PROTOCOL=$PROTOCOL | \
          sed -E 's/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/xxx.xxx.xxx.xxx/g'
            

      # Create client VM which will start benchmark
      - name: Create Client
        run: |-
          INTERNAL_IP=`gcloud compute instances list --filter="name=$SERVER_INSTANCE" --format='value(networkInterfaces[0].networkIP)'`
          gcloud compute instances create-with-container $CLIENT_INSTANCE \
            --machine-type=$MACHINE_TYPE \
            --scopes="userinfo-email,storage-rw" \
            --zone=$ZONE \
            --tags=benchmark-tag \
            --network=default \
            --container-image=gcr.io/$PROJECT_ID/$CLIENT_INSTANCE-image:latest \
            --container-restart-policy=never \
            --container-env="BUCKET=$BUCKET,SERVER_HOST=${INTERNAL_IP},SERVER_PORT=8080,SIMULATIONS=$SIMULATIONS,INCREMENT=$INCREMENT,STEPS=$STEPS,DURATION=$DURATION,APP=$APP,PROTOCOL=$PROTOCOL" | \
          sed -E 's/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/xxx.xxx.xxx.xxx/g'

      # Wait for the results (one zip file for the application + gh-benchmark.json) (add 10 minutes for each test to let gatling be able to collect results)
      - name: Wait for test result
        run: |-
          nr_simulations=0
          for simulation in $(echo ${SIMULATIONS} | tr ";" "\n"); do
            nr_simulations=$(expr $nr_simulations + 1)
          done
          max_wait=$(expr $DURATION \* $nr_simulations)
          delta=$(expr 10 \* $nr_simulations)
          max_wait=$(expr $max_wait + $delta)
          ${SCRIPTS_DIR}/wait-for-gs-bucket-file.sh gs://$BUCKET/results 2 $max_wait
          gsutil cp gs://$BUCKET/results/gh-benchmark.json .

      # Compute performance trends and send an alert in case of performance regression
      - name: Generate trends report
        uses: benchmark-action/github-action-benchmark@v1.15.0
        with:
          name: Trends for ${{ env.APP_PROTOCOL }}
          tool: 'customBiggerIsBetter'
          output-file-path: ./gh-benchmark.json
          benchmark-data-dir-path: bench/${{ env.APP_PROTOCOL }}/Trends
          max-items-in-chart: 100
          auto-push: false
          alert-threshold: ${{ env.ALERT_THRESHOLD }}
          fail-threshold: ${{ env.ALERT_THRESHOLD }}
          fail-on-alert: true
          comment-on-alert: false
          github-token: ${{ env.GH_TOKEN }}

      - name: Prepare results
        run: |-
          . ${SCRIPTS_DIR}/libs.sh
          git checkout gh-pages
          gsutil cp gs://$BUCKET/results/bench.tgz .
          tar zxf bench.tgz
          rm -f bench.tgz
          build-results-readme bench > README.md
          update_benchmark_history bench/$APP_PROTOCOL/Trends/.history "${{ needs.init-benchmark.outputs.commits }}" 
          transform_benchmark_json_data bench/$APP_PROTOCOL/Trends/data.js "Trends for $APP_PROTOCOL" $JOB_URL $GITHUB_RUN_ID "${{ needs.init-benchmark.outputs.commits_diff }}" 
          cp -f ${SCRIPTS_DIR}/benchmark-index-template.html bench/$APP_PROTOCOL/Trends/index.html

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: |
            README.md
            bench
          if-no-files-found: warn
          retention-days: 90

      - name: Cleanup GCP resources
        if: always()
        run: |-
          set +e
          echo "client instance container logs:"
          container_id=$(gcloud compute ssh $CLIENT_INSTANCE --zone=$ZONE --project=$GCP_PROJECT --command "docker ps -a" | \
            tr '\r' '\n' | grep $CLIENT_INSTANCE | cut -d ' ' -f 1)
          gcloud compute ssh $CLIENT_INSTANCE --zone=$ZONE --project=$GCP_PROJECT --command "docker logs $container_id"
          echo "Deleting client instance"
          gcloud compute instances delete $CLIENT_INSTANCE --quiet --zone $ZONE | echo
          echo "server instance container logs:"
          container_id=$(gcloud compute ssh $SERVER_INSTANCE --zone=$ZONE --project=$GCP_PROJECT --command "docker ps -a" | \
            tr '\r' '\n' | grep $SERVER_INSTANCE | cut -d ' ' -f 1)
          gcloud compute ssh $SERVER_INSTANCE --zone=$ZONE --project=$GCP_PROJECT --command "docker logs $container_id"
          echo "Deleting server instance"
          gcloud compute instances delete $SERVER_INSTANCE --quiet --zone $ZONE | echo
          echo "Deleting files from bucket"
          gsutil rm -f gs://$BUCKET/apps/* | echo
          gsutil rm -f gs://$BUCKET/results/* | echo
