name: containers-deploy

on:
  workflow_call:
    inputs:
      frontend-vm:
        type: string
        description: 'The frontend vm to build an image for:'
        default: ''
        required: true
      client-vm:
        type: string
        description: 'The client vm to build an image for:'
        default: ''
        required: true

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  CLIENT_VM: ${{ inputs.client-vm }}
  FRONTEND_VM: ${{ inputs.frontend-vm }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  setup-containers:
    name: Create images for VMs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # GCP authentication via credentials json (TODO replace by OpenId)
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Purge old containers
    - name: Purge old images
      run: |-
        gcloud container images list-tags gcr.io/$PROJECT_ID/$FRONTEND_VM-image \
          --format="get(digest)" | \
          awk -v image_path="gcr.io/$PROJECT_ID/$FRONTEND_VM-image@" '{print image_path $1}' | \
          xargs -r gcloud container images delete --force-delete-tags --quiet
        gcloud container images list-tags gcr.io/$PROJECT_ID/$CLIENT_VM-image \
          --format="get(digest)" | \
          awk -v image_path="gcr.io/$PROJECT_ID/$CLIENT_VM-image@" '{print image_path $1}' | \
          xargs -r gcloud container images delete --force-delete-tags --quiet

    # Build the Docker images
    - name: Build containers
      run: |-
        git checkout ${GITHUB_REF##*/}
        ./gradlew gatling:build
        cp gatling/build/libs/gatling-1.0-SNAPSHOT-all.jar /tmp
        git checkout main
        cp /tmp/gatling-1.0-SNAPSHOT-all.jar containers/client/
        docker build --tag "gcr.io/$PROJECT_ID/$FRONTEND_VM-image:latest" containers/server
        docker build --tag "gcr.io/$PROJECT_ID/$CLIENT_VM-image:latest" containers/client

    # Push the Docker image to Google Container Registry
    - name: Push containers to GCR
      run: |-
        docker push "gcr.io/$PROJECT_ID/$FRONTEND_VM-image:latest"
        docker push "gcr.io/$PROJECT_ID/$CLIENT_VM-image:latest"
