name: containers-deploy

on:
  workflow_dispatch:

jobs:
  container-deploy:
    uses: ./.github/actions/ci-container-deploy.yml@main
    secrets: inherit
    with:
      gatling-image: benchmark-gatling-image
      server-image: benchmark-server-image
